version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: keep-chats-bot-postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    command: -p ${PG_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - ${PG_PORT}
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - main

  app:
    image: ${DOCKER_IMAGE:-ghcr.io/passimx/proof-bot:latest}
    container_name: keep-chats-bot
    restart: always
    env_file: .env
    environment:
      PG_HOST: postgres
      PG_PORT: ${PG_PORT}
      PORT: ${PORT:-2000}
    ports:
      - "${PORT:-2000}:${PORT:-2000}"
    depends_on:
      - postgres
    networks:
      - main

networks:
  main:
    driver: bridge